## YAML Template.
---
runtime: php55
api_version: 1

handlers:

- url: /
  script: index.php

- url: /(.+\.(gif|png|jpg|jpeg|ico|css|js))$
  static_files: \1
  upload: .+\.(gif|png|jpg|jpeg|ico|css|js)$
  application_readable: true
  
- url: /(.+\.php|html)$
  script: \1